services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    volumes:
      - './app:/app'
      - './entrypoint.sh:/entrypoint.sh'
    environment:
      - NODE_ENV=development
