import SessionProvider from '@/SessionProvider'
import { getServerSession } from 'next-auth'
import { ReduxProvider } from '@/redux/provider'

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export default function RootLayout({ children }) {
    const session = getServerSession()
    return (
        <html lang="en">
            <body>
                <SessionProvider session={session}>
                    <ReduxProvider>{children}</ReduxProvider>
                </SessionProvider>
            </body>
        </html>
    )
}
